import { resolveWorkflowPackageConfig, type ResolvedWorkflowPackageConfig } from '../../config.js'
import { openWorkflowStorageAnchor, acquireWorkflowStorageLease, type WorkflowStorageAnchor, type WorkflowStorageLease } from './lease.js'
import { initializePrivateLayout, type WorkflowStorageLayout } from './private-root.js'
import { FileWorkflowRunStore } from './manifest-store.js'
import { recoverWorkflowStorage } from './recovery.js'
export * from './lease.js'; export * from './private-root.js'; export * from './bounded-file.js'; export * from './manifest-types.js'; export * from './manifest-codec.js'; export * from './details-codec.js'; export * from './manifest-store.js'; export * from './run-files.js'; export * from './recovery.js'
export interface WorkflowStorage { readonly anchor: WorkflowStorageAnchor; readonly lease: WorkflowStorageLease; readonly layout: WorkflowStorageLayout; readonly store: FileWorkflowRunStore; dispose(): Promise<void> }
/** Bootstrap the leased storage root and eagerly recover retained state. */
export async function openWorkflowStorage(config: ResolvedWorkflowPackageConfig): Promise<WorkflowStorage> { const anchor=await openWorkflowStorageAnchor({runsRoot:config.runsRoot});let lease:WorkflowStorageLease|undefined;try{lease=await acquireWorkflowStorageLease(anchor);const layout=await initializePrivateLayout(anchor,lease);const store=new FileWorkflowRunStore({runsRoot:config.runsRoot,maxManifestBytes:config.maxManifestBytes,maxRunDetailsBytes:config.maxRunDetailsBytes,maxRunStoreBytes:config.maxRunStoreBytes,maxRetainedRunsPerSession:config.maxRetainedRunsPerSession,maxWorkflowNamesPerSession:config.maxWorkflowNamesPerSession,maxMembersPerRun:config.maxMembersPerRun,maxRecoveryEntries:config.maxRecoveryEntries,maxTerminalResultBytes:config.maxTerminalResultBytes,memberOutcomeMaxBytes:config.memberOutcomeMaxBytes,maxLogLines:config.maxLogLines,maxLogLineBytes:config.maxLogLineBytes},lease);await recoverWorkflowStorage({root:config.runsRoot},store,{maxRecoveryEntries:config.maxRecoveryEntries});let disposed=false;return {anchor,lease,layout,store,async dispose(){if(disposed)return;disposed=true;await store.dispose();await lease!.release()}}}catch(error){if(lease)await lease.release().catch(()=>{});else await anchor.close().catch(()=>{});throw error}}
