import { randomBytes } from 'node:crypto'
import type { WorkflowDefinition } from '../registry/types.js'
import type { WorkflowRegistry } from '../registry/index.js'
import type { WorkflowRunStore, WorkflowRunHeadRecord, WorkflowRunDetailPayloadV2 } from './storage/manifest-types.js'
import { FileWorkflowRunStore } from './storage/manifest-store.js'
import { renderWorkflowCompletionNotice, WorkflowCompletionNotifier } from './completion-notice.js'
import { snapshotWorkflowJsonValue } from './value-view.js'
import type {
  WorkflowLaunched, WorkflowRunHead, WorkflowRunAction, WorkflowRunStatus,
  WorkflowValidation, WorkflowRunControlResult, SupervisedWorkflowRunId, WorkflowRunChange,
  WorkflowGateInfo, WorkflowGateId, WorkflowRunCursor, WorkflowRunListPage, WorkflowRunMemberPage,
  WorkflowRunMemberDetail, WorkflowRunLogPage, WorkflowRunResultView, WorkflowRunArtifactPage,
  WorkflowRunArtifactRequest, WorkflowRunDetail, WorkflowRunMemberRequest, WorkflowRunListRequest, WorkflowRunFeedEpoch,
} from './types.js'
import { WorkflowPackageError } from '../invariant.js'
export * from './types.js'; export * from './value-view.js'; export * from './completion-notice.js'

export interface SupervisorConfig { readonly defaultAgentBudget?:number;readonly maxAgentBudget?:number;readonly maxConcurrentAgents?:number;readonly maxActiveRunsPerSession?:number;readonly maxActiveRunsGlobal?:number;readonly saveScope?:'project'|'user';readonly completionNoticeMaxBytes?:number;readonly memberOutcomeMaxBytes?:number;readonly maxRetainedRunsPerSession?:number;readonly maxWorkflowNamesPerSession?:number;readonly maxRecoveryEntries?:number;readonly maxMembersPerRun?:number;readonly maxManifestBytes?:number;readonly maxRunDetailsBytes?:number;readonly maxRunStoreBytes?:number;readonly maxLogLines?:number;readonly maxLogLineBytes?:number;readonly maxActiveRuns?:number }
export interface WorkflowLaunchSpec { readonly definition?:WorkflowDefinition;readonly script?:string;readonly meta?:any;readonly args?:Readonly<Record<string,unknown>>;readonly agentBudget?:number;readonly parent:any;readonly signal?:AbortSignal }
export interface WorkflowValidateSpec extends Omit<WorkflowLaunchSpec,'definition'|'parent'>{readonly definition?:WorkflowDefinition;readonly parent?:any;readonly filename:string}
export interface WorkflowGateRequest {readonly info:{readonly id:SupervisedWorkflowRunId;readonly displayName:string;readonly name:string};readonly executionId:string;readonly gateId:WorkflowGateId;readonly gate:WorkflowGateInfo;readonly parent:any;readonly signal:AbortSignal}

type WorkflowCheckpoint = { readonly journal: readonly unknown[]; readonly agentSpend: number; readonly agentSeq: number }
type Attempt = { readonly handle:any; readonly executionId:string; checkpoint?:WorkflowCheckpoint; generation:number }
type InternalRun = { readonly id:SupervisedWorkflowRunId; readonly sessionId:string; readonly meta:any; readonly script:string; readonly args:Record<string,unknown>; readonly parent:any; readonly runDirectory:string; readonly scriptPath:string; head:WorkflowRunHeadRecord; attempt?:Attempt; generation:number; queue:Promise<unknown>; builtIn:boolean }
const id=():SupervisedWorkflowRunId=>randomBytes(16).toString('hex') as SupervisedWorkflowRunId
const sessionOf=(agent:any):string=>String(agent?.session?.id ?? agent?.session?.header?.id ?? agent?.sessionId ?? agent?.id ?? 'unknown-session')
const descriptionOf=(meta:any):string=>typeof meta?.description==='string'?meta.description:''
function headView(head:WorkflowRunHeadRecord):WorkflowRunHead {return {runId:head.runId as SupervisedWorkflowRunId,displayName:head.displayName,name:head.name,description:head.description??'',status:head.status,phase:head.phase,budget:head.budget,memberCounts:head.memberCounts,startedAt:head.startedAt,settledAt:head.settledAt,allowedActions:(head.allowedActions??[]) as WorkflowRunAction[],revision:head.revision,detailRevision:head.detailRevision,membersRevision:head.membersRevision,logsRevision:head.logsRevision,resultRevision:head.resultRevision,artifactsRevision:head.artifactsRevision}}

/** Own detached workflow attempts and durable lifecycle state. */
export class WorkflowSupervisor {
  static readonly inject=['workflowEngine','workflows'] as const
  private readonly ctx:any; private readonly config:Required<SupervisorConfig>; private readonly store:WorkflowRunStore; private readonly registry?:WorkflowRegistry; private readonly runs=new Map<string,InternalRun>(); private readonly byDisplay=new Map<string,InternalRun>(); private readonly activeSessions=new Map<string,number>(); private admission=true; private disposed=false; private readonly notifier:WorkflowCompletionNotifier
  constructor(ctx:any, config:SupervisorConfig={}, store?:WorkflowRunStore){this.ctx=ctx;this.config={defaultAgentBudget:config.defaultAgentBudget??128,maxAgentBudget:config.maxAgentBudget??1024,maxConcurrentAgents:config.maxConcurrentAgents??32,maxActiveRunsPerSession:config.maxActiveRunsPerSession??64,maxActiveRunsGlobal:config.maxActiveRunsGlobal??1024,saveScope:config.saveScope??'project',completionNoticeMaxBytes:config.completionNoticeMaxBytes??16384,memberOutcomeMaxBytes:config.memberOutcomeMaxBytes??131072,maxRetainedRunsPerSession:config.maxRetainedRunsPerSession??256,maxWorkflowNamesPerSession:config.maxWorkflowNamesPerSession??4096,maxRecoveryEntries:config.maxRecoveryEntries??4096,maxMembersPerRun:config.maxMembersPerRun??2048,maxManifestBytes:config.maxManifestBytes??8388608,maxRunDetailsBytes:config.maxRunDetailsBytes??33554432,maxRunStoreBytes:config.maxRunStoreBytes??536870912,maxLogLines:config.maxLogLines??4096,maxLogLineBytes:config.maxLogLineBytes??65536,maxActiveRuns:config.maxActiveRuns??1024};this.store=store??(ctx?.workflowStore as WorkflowRunStore);this.registry=ctx?.workflows;this.notifier=new WorkflowCompletionNotifier(ctx,{...(this.store as any)})}
  async initialize(signal?:AbortSignal):Promise<void>{signal?.throwIfAborted();await this.store?.initialize?.(signal)}
  private emit(name:string,...args:unknown[]):void{try{this.ctx?.emit?.(name,...args);this.ctx?.dispatch?.(name,...args)}catch(error){this.ctx?.logger?.warn?.('workflow supervisor observer failed',error)}}
  private async enqueue(run:InternalRun,operation:()=>Promise<any>):Promise<any>{const previous=run.queue;let release!:()=>void;run.queue=new Promise<void>(resolve=>{release=resolve});await previous;try{return await operation()}finally{release()}}
  /** Admit one run durably, attach an attempt, publish it, and return before settlement. */
  async start(spec:WorkflowLaunchSpec):Promise<WorkflowLaunched>{if(!this.admission||this.disposed)throw new WorkflowPackageError('workflow supervisor is shutting down','WORKFLOW_INVALID_STATE');if(!spec.parent)throw new WorkflowPackageError('workflow start requires a calling agent','WORKFLOW_INVALID_STATE');const definition=spec.definition;const meta=definition?{name:definition.name,description:definition.description,...(definition.whenToUse===undefined?{}:{whenToUse:definition.whenToUse}),...(definition.phases===undefined?{}:{phases:definition.phases})}:spec.meta;if(!meta||typeof meta.name!=='string'||typeof meta.description!=='string')throw new WorkflowPackageError('workflow metadata is invalid','WORKFLOW_DEFINITION_INVALID');const script=definition?.script??spec.script;if(typeof script!=='string')throw new WorkflowPackageError('workflow script is missing','WORKFLOW_DEFINITION_INVALID');const sessionId=sessionOf(spec.parent);const active=[...this.runs.values()].filter(r=>r.sessionId===sessionId&&!['completed','failed','cancelled','interrupted'].includes(r.head.status)).length;if(active>=this.config.maxActiveRunsPerSession||this.runs.size>=this.config.maxActiveRunsGlobal)throw new WorkflowPackageError('workflow active-run limit reached','WORKFLOW_LIMIT');const runId=id();let inserted:WorkflowRunHeadRecord;const budget=spec.agentBudget??this.config.defaultAgentBudget;const store=this.store;if(!store)throw new WorkflowPackageError('workflow storage is unavailable','WORKFLOW_STORAGE_UNSUPPORTED');inserted=await store.insertWithNextDisplayName({sessionId,name:meta.name,runId,script,description:meta.description,budgetTotal:budget},identity=>({head:{description:meta.description,status:'running',budget:{total:budget,spent:0,remaining:budget},memberCounts:{total:0,running:0,completed:0,failed:0,cancelled:0},startedAt:Date.now(),detailRevision:1,membersRevision:1,logsRevision:1,resultRevision:1,artifactsRevision:1},detail:{members:[],logs:[]}}));const run:InternalRun={id:runId,sessionId,meta,script,args:{...(spec.args??{})},parent:spec.parent,runDirectory:inserted.runDirectory,scriptPath:inserted.scriptPath??'',head:inserted,generation:1,queue:Promise.resolve(),builtIn:inserted.name.startsWith('builtin-')};this.runs.set(runId,run);this.byDisplay.set(inserted.displayName,run);this.activeSessions.set(sessionId,(this.activeSessions.get(sessionId)??0)+1);this.emit('workflows/run-start',{id:runId,displayName:inserted.displayName,name:meta.name});this.emit('workflows/run-change',{kind:'invalidate',sessionId,revision:inserted.revision});void this.runAttempt(run,spec);return {status:'started',displayName:inserted.displayName,runId:runId as SupervisedWorkflowRunId,scriptPath:inserted.scriptPath}}
  private async runAttempt(run:InternalRun,spec:WorkflowLaunchSpec):Promise<void>{const engine=this.ctx?.workflowEngine;let handle:any;try{if(!engine?.start)throw new Error('workflow engine is unavailable');handle=engine.start({script:run.script,meta:run.meta,args:run.args,parent:run.parent,signal:undefined,replay:{},scratch:undefined,maxTotalAgents:this.config.defaultAgentBudget,deferStart:true});run.attempt={handle,executionId:id(),generation:run.generation};if(typeof handle.release==='function')handle.release();const result=await handle.result;await handle.dispose?.();let checkpoint:any;try{checkpoint=handle.checkpoint?.()}catch{};if(checkpoint)run.attempt.checkpoint=checkpoint;const status=result?.stopReason==='completed'?'completed':result?.stopReason==='cancelled'?'cancelled':'failed';await this.commitStatus(run,status,result?.error,result?.value); }catch(error){try{await handle?.dispose?.()}catch{};await this.commitStatus(run,'failed',error instanceof Error?error.message:String(error))}}
  private async commitStatus(run:InternalRun,status:WorkflowRunStatus,error?:string,value?:unknown):Promise<void>{await this.enqueue(run,async()=>{if(['completed','failed','cancelled','interrupted'].includes(run.head.status))return;const next:any={...run.head,status,stopReason:status==='completed'?'completed':status==='cancelled'?'cancelled':status==='interrupted'?'interrupted':'error',error,settledAt:Date.now(),allowedActions:[],executionAvailable:true};if(value!==undefined){const detail:any={members:[],logs:[],result:{state:'available',value}};try{run.head=await this.store.commitRun({sessionId:run.sessionId,runId:run.id,expectedRevision:run.head.revision,head:next,detail})}catch{run.head={...run.head,...next,revision:run.head.revision+1}}}else{try{run.head=await this.store.commitTerminalAndClaimNotice({sessionId:run.sessionId,runId:run.id,expectedRevision:run.head.revision,head:next})}catch{run.head={...run.head,...next,revision:run.head.revision+1}}}this.emit('workflows/run-end',{id:run.id,displayName:run.head.displayName,name:run.meta.name},{stopReason:status==='completed'?'completed':status==='cancelled'?'cancelled':'error',error,agentsStarted:run.head.memberCounts.total});this.emit('workflows/run-change',{kind:'invalidate',sessionId:run.sessionId,revision:run.head.revision});void this.notifier.notify({runId:run.id,displayName:run.head.displayName,status:status==='completed'?'completed':status==='cancelled'?'cancelled':status==='interrupted'?'interrupted':'failed',error,result:value===undefined?undefined:{state:'available',content:{kind:'value',value:snapshotWorkflowJsonValue(value)},totalBytes:0,truncated:false}});this.activeSessions.set(run.sessionId,Math.max(0,(this.activeSessions.get(run.sessionId)??1)-1))})}
  async pause(displayName:string,agent:any,signal?:AbortSignal):Promise<WorkflowRunHead>{const run=this.requireOwned(displayName,agent);return this.enqueue(run,async()=>{signal?.throwIfAborted();if(run.head.status!=='running')throw new WorkflowPackageError(`workflow "${displayName}" is not running (${run.head.status})`,'WORKFLOW_INVALID_STATE');run.head={...run.head,status:'paused',revision:run.head.revision+1,allowedActions:['resume','stop']};run.attempt?.handle.cancel?.('paused');return headView(run.head)})}
  async resume(displayName:string,agent:any,signal?:AbortSignal):Promise<WorkflowRunHead>{const run=this.requireOwned(displayName,agent);return this.enqueue(run,async()=>{signal?.throwIfAborted();if(run.head.status==='budget-limited')throw new WorkflowPackageError(`workflow "${displayName}" requires a higher agent_budget to resume`,'WORKFLOW_INVALID_STATE');if(!['paused','needs-input'].includes(run.head.status))throw new WorkflowPackageError(`workflow "${displayName}" is not resumable (${run.head.status})`,'WORKFLOW_INVALID_STATE');run.head={...run.head,status:'running',revision:run.head.revision+1,allowedActions:['pause','stop']};return headView(run.head)})}
  async resumeById(runId:SupervisedWorkflowRunId,agent:any,higherBudget?:number,signal?:AbortSignal):Promise<WorkflowRunHead>{const run=this.runs.get(runId);if(!run||run.parent!==agent)throw new WorkflowPackageError('workflow run is not owned by this Agent','WORKFLOW_RUN_NOT_OWNED');if(run.head.status==='budget-limited'&&(!Number.isSafeInteger(higherBudget)||higherBudget!<=run.head.budget.total||higherBudget!>1024))throw new WorkflowPackageError(`workflow "${run.head.displayName}" requires a higher agent_budget to resume`,'WORKFLOW_INVALID_STATE');return this.resume(run.head.displayName,agent,signal)}
  async resumeGate(_runId:SupervisedWorkflowRunId,_executionId:string,_gateId:WorkflowGateId,_agent:any,_signal?:AbortSignal):Promise<boolean>{return false}
  async stop(displayName:string,agent:any,signal?:AbortSignal):Promise<WorkflowRunHead>{const run=this.requireOwned(displayName,agent);return this.enqueue(run,async()=>{signal?.throwIfAborted();if(['completed','failed','cancelled','interrupted'].includes(run.head.status))throw new WorkflowPackageError(`workflow "${displayName}" already settled (${run.head.status})`,'WORKFLOW_INVALID_STATE');run.attempt?.handle.cancel?.('stopped');run.head={...run.head,status:'cancelled',stopReason:'cancelled',settledAt:Date.now(),revision:run.head.revision+1,allowedActions:[]};return headView(run.head)})}
  async save(displayName:string,agent:any,scope:'project'|'user'=this.config.saveScope,signal?:AbortSignal):Promise<string>{const run=this.requireOwned(displayName,agent);if(run.builtIn)throw new WorkflowPackageError(`workflow "${displayName}" is a built-in: save an edited copy under a new meta.name`,'WORKFLOW_INVALID_STATE');if(run.head.numberedHandle)throw new WorkflowPackageError(`workflow "${displayName}" is a numbered handle: save an edited copy under a new unique meta.name`,'WORKFLOW_INVALID_STATE');if(run.head.status==='interrupted')throw new WorkflowPackageError(`workflow "${displayName}" cannot be saved after process interruption`,'WORKFLOW_INVALID_STATE');if(!this.registry)throw new WorkflowPackageError('workflow registry is unavailable','WORKFLOW_REGISTRY_DISABLED');const saved=await this.registry.save({meta:run.meta,script:run.script},{scope,cwd:agent?.session?.header?.cwd,signal});return saved.path}
  async validate(spec:WorkflowValidateSpec):Promise<WorkflowValidation>{if(!spec.parent)return {ok:false,status:'error',error:'validate_only requires a calling agent'};try{const engine=this.ctx?.workflowEngine;const meta=spec.definition?{name:spec.definition.name,description:spec.definition.description,whenToUse:spec.definition.whenToUse,phases:spec.definition.phases}:spec.meta;if(engine?.validate){const result=await engine.validate({script:spec.definition?.script??spec.script,meta,args:spec.args,maxTotalAgents:spec.agentBudget,signal:spec.signal});return result}return {ok:true,status:'completed',value:null}}catch(error){return {ok:false,status:'error',error:`${spec.filename}: ${error instanceof Error?error.message:String(error)}`}}}
  private requireOwned(displayName:string,agent:any):InternalRun{const run=this.byDisplay.get(displayName);if(!run)throw new WorkflowPackageError(`workflow "${displayName}" was not found`,'WORKFLOW_RUN_NOT_FOUND');if(run.parent!==agent&&sessionOf(run.parent)!==sessionOf(agent))throw new WorkflowPackageError(`workflow "${displayName}" is not owned by this Agent`,'WORKFLOW_RUN_NOT_OWNED');return run}
  async list(agent:any,request:WorkflowRunListRequest={}):Promise<WorkflowRunListPage>{const sessionId=sessionOf(agent);const rows=(await this.store.readSession(sessionId)).map(headView);return {epoch:'local' as WorkflowRunFeedEpoch,sessionRevision:rows.reduce((m,r)=>Math.max(m,r.revision),0),items:rows.slice(request.cursor?Number(request.cursor):0,(request.cursor?Number(request.cursor):0)+(request.limit??50)),total:rows.length}}
  async detail(agent:any,runId:SupervisedWorkflowRunId):Promise<WorkflowRunDetail>{const run=this.runs.get(runId);if(!run||sessionOf(run.parent)!==sessionOf(agent))throw new WorkflowPackageError('workflow run is not owned by this Agent','WORKFLOW_RUN_NOT_OWNED');return {run:headView(run.head),scriptPath:run.scriptPath}}
  async closeAdmission():Promise<void>{this.admission=false}
  closeAdmissionSync():void{this.admission=false}
  async whenOwnerQuiescent(_agent:any,_signal?:AbortSignal):Promise<void>{await Promise.all([...this.runs.values()].map(r=>r.queue))}
  async recordingSnapshot(agent:any,runId:SupervisedWorkflowRunId):Promise<any>{const run=this.runs.get(runId);if(!run||sessionOf(run.parent)!==sessionOf(agent))return undefined;return {runId,displayName:run.head.displayName,status:run.head.status,members:[],result:undefined}}
  async dispose():Promise<void>{if(this.disposed)return;this.disposed=true;this.admission=false;for(const run of this.runs.values())run.attempt?.handle.cancel?.('supervisor disposed');await Promise.all([...this.runs.values()].map(r=>r.queue));await this.store?.dispose?.();await this.notifier.dispose()}
}
