import { readFile } from 'node:fs/promises'
import { parseDefinitionFile } from '../registry/definition.js'
import type { WorkflowRegistry } from '../registry/index.js'
import type { WorkflowSupervisor } from '../supervisor/index.js'
import type { WorkflowToolArgs } from './schema.js'
import { parseWorkflowToolRequest, WORKFLOW_TOOL_SCHEMA } from './schema.js'
export * from './schema.js'
export interface ResolvedWorkflowSource { readonly script:string;readonly meta:any;readonly args:Record<string,unknown>;readonly filename:string }
/** Resolve one validated model source through registry or no-follow filesystem APIs. */
export async function resolveWorkflowSource(ctx:any,request:ReturnType<typeof parseWorkflowToolRequest>,options:{agent?:any;signal?:AbortSignal;definitionMaxBytes?:number}={}):Promise<ResolvedWorkflowSource>{if(request.kind==='resume')throw new Error('resume request has no source');if(request.source.kind==='name'){const definition=await (ctx.workflows as WorkflowRegistry).get(request.source.name,{cwd:options.agent?.session?.header?.cwd,signal:options.signal});if(!definition)throw new Error(`no saved workflow named "${request.source.name}"`);return {script:definition.script,meta:{name:definition.name,description:definition.description,whenToUse:definition.whenToUse,phases:definition.phases},args:request.args,filename:definition.path}}if(request.source.kind==='script'){return {script:request.source.script,meta:request.source.meta,args:request.args,filename:'<inline workflow>'}}const path=request.source.path;let bytes:Uint8Array;if(ctx.fs?.readBytesNoFollow)bytes=await ctx.fs.readBytesNoFollow(path,options.agent?.session?.header?.cwd?{cwd:options.agent.session.header.cwd}:{},options.signal,options.definitionMaxBytes??1_048_576);else bytes=new Uint8Array(await readFile(path));const text=new TextDecoder('utf8',{fatal:true}).decode(bytes);if(path.endsWith('.workflow.json')){const stem=path.replaceAll('\\','/').split('/').at(-1)!.slice(0,-'.workflow.json'.length);const parsed=parseDefinitionFile(text,path,stem);return {script:parsed.script,meta:{name:parsed.name,description:parsed.description,whenToUse:parsed.whenToUse,phases:parsed.phases},args:request.args,filename:path}}if(!request.source.meta)throw new Error('workflow bare script_path requires the meta object');return {script:text,meta:request.source.meta,args:request.args,filename:path}}
/** Create a model-facing workflow operation with background ownership. */
export function createWorkflowTool(services:{registry:WorkflowRegistry;supervisor:WorkflowSupervisor;recorder?:any}){return {name:'workflow',schema:WORKFLOW_TOOL_SCHEMA,async execute(raw:WorkflowToolArgs,exec:any){if(!exec?.agent)throw new Error('workflow tool requires a calling agent (exec.agent was undefined)');const request=parseWorkflowToolRequest(raw);if(request.kind==='resume'){const run=await services.supervisor.resumeById(request.runId as any,exec.agent,request.agentBudget);return {status:'resumed',displayName:run.displayName,runId:run.runId}}const source=await resolveWorkflowSource({workflows:services.registry,fs:exec.fs},request,{agent:exec.agent,signal:exec.signal});if(request.validateOnly){const result=await services.supervisor.validate({script:source.script,meta:source.meta,args:source.args,parent:exec.agent,filename:source.filename,agentBudget:request.agentBudget});return {status:'validated',...(result as any)}}const start=()=>services.supervisor.start({script:source.script,meta:source.meta,args:source.args,parent:exec.agent,agentBudget:request.agentBudget});const launched=services.recorder?await services.recorder.launch(exec.agent.session,start):await start();return {status:'started',displayName:launched.displayName,runId:launched.runId,script_path:launched.scriptPath}}}}
