/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { WorkflowDefinitionListPage, WorkflowDefinitionListRequest } from '@zaalipro/dsh-workflows/registry'
import type { WorkflowRemoteResult, WorkflowRunArtifactChunk, WorkflowRunArtifactPage, WorkflowRunArtifactRequest, WorkflowRunArtifactsRequest, WorkflowRunControlRequest, WorkflowRunControlResult, WorkflowRunDetail, WorkflowRunListPage, WorkflowRunListRequest, WorkflowRunLogPage, WorkflowRunLogsRequest, WorkflowRunMemberDetail, WorkflowRunMemberPage, WorkflowRunMemberRequest, WorkflowRunMembersRequest, WorkflowRunRequest, WorkflowRunResultView } from '@zaalipro/dsh-workflows/supervisor'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b666c6f77446566696e6974696f6e73 {
    list: (agentId: SessionId, request: WorkflowDefinitionListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowDefinitionListPage>>>
  }
  interface TypertRemoteNamespace$776f726b666c6f7752756e73 {
    artifact: (agentId: SessionId, request: WorkflowRunArtifactRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactChunk>>>
    artifacts: (agentId: SessionId, request: WorkflowRunArtifactsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactPage>>>
    control: (agentId: SessionId, request: WorkflowRunControlRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunControlResult>>>
    detail: (agentId: SessionId, request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunDetail>>>
    list: (agentId: SessionId, request: WorkflowRunListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunListPage>>>
    logs: (agentId: SessionId, request: WorkflowRunLogsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunLogPage>>>
    memberDetail: (agentId: SessionId, request: WorkflowRunMemberRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberDetail>>>
    members: (agentId: SessionId, request: WorkflowRunMembersRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberPage>>>
    result: (agentId: SessionId, request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunResultView>>>
  }
  interface TypertRemoteMap {
    'workflowDefinitions/list': (agentId: SessionId, request: WorkflowDefinitionListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowDefinitionListPage>>>
    'workflowRuns/artifact': (agentId: SessionId, request: WorkflowRunArtifactRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactChunk>>>
    'workflowRuns/artifacts': (agentId: SessionId, request: WorkflowRunArtifactsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactPage>>>
    'workflowRuns/control': (agentId: SessionId, request: WorkflowRunControlRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunControlResult>>>
    'workflowRuns/detail': (agentId: SessionId, request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunDetail>>>
    'workflowRuns/list': (agentId: SessionId, request: WorkflowRunListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunListPage>>>
    'workflowRuns/logs': (agentId: SessionId, request: WorkflowRunLogsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunLogPage>>>
    'workflowRuns/memberDetail': (agentId: SessionId, request: WorkflowRunMemberRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberDetail>>>
    'workflowRuns/members': (agentId: SessionId, request: WorkflowRunMembersRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberPage>>>
    'workflowRuns/result': (agentId: SessionId, request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunResultView>>>
  }
  interface TypertRemoteNamespaceMap {
    'workflowDefinitions': TypertRemoteNamespace$776f726b666c6f77446566696e6974696f6e73
    'workflowRuns': TypertRemoteNamespace$776f726b666c6f7752756e73
  }
  interface TypertRemoteScopeMap {
    'agent:workflowDefinitions/list': (request: WorkflowDefinitionListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowDefinitionListPage>>>
    'agent:workflowRuns/artifact': (request: WorkflowRunArtifactRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactChunk>>>
    'agent:workflowRuns/artifacts': (request: WorkflowRunArtifactsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunArtifactPage>>>
    'agent:workflowRuns/control': (request: WorkflowRunControlRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunControlResult>>>
    'agent:workflowRuns/detail': (request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunDetail>>>
    'agent:workflowRuns/list': (request: WorkflowRunListRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunListPage>>>
    'agent:workflowRuns/logs': (request: WorkflowRunLogsRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunLogPage>>>
    'agent:workflowRuns/memberDetail': (request: WorkflowRunMemberRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberDetail>>>
    'agent:workflowRuns/members': (request: WorkflowRunMembersRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunMemberPage>>>
    'agent:workflowRuns/result': (request: WorkflowRunRequest, signal?: AbortSignal) => Promise<RemoteResult<WorkflowRemoteResult<WorkflowRunResultView>>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
