/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)).readonly()])
const JsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)).readonly()])
const _zaalipro_dsh_workflows_workflowDefinitions_list_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowDefinitions_list_parameter_1$schema = z.object({
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const _zaalipro_dsh_workflows_workflowDefinitions_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'whenToUse': z.union([z.undefined(), z.string()]).readonly().optional(),
  'scope': z.union([z.literal("bundled"), z.literal("project"), z.literal("user")]).readonly(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'total': z.number().readonly(),
  'revision': z.number().readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_artifact_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_artifact_parameter_1$schema = z.object({
  'name': z.string().readonly(),
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'maxBytes': z.union([z.undefined(), z.number()]).readonly().optional(),
  'expectedRevision': z.union([z.undefined(), z.number()]).readonly().optional(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_artifact_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'artifact': z.object({
  'name': z.string().readonly(),
  'bytes': z.number().readonly(),
}).readonly(),
  'text': z.string().readonly(),
  'offsetBytes': z.number().readonly(),
  'returnedBytes': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'revision': z.number().readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_artifacts_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_artifacts_parameter_1$schema = z.object({
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_artifacts_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'name': z.string().readonly(),
  'bytes': z.number().readonly(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'omitted': z.number().readonly(),
  'total': z.number().readonly(),
  'revision': z.number().readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_control_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_control_parameter_1$schema = z.object({
  'action': z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")]).readonly(),
  'expectedRevision': z.number().readonly(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_control_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_detail_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_detail_parameter_1$schema = z.object({
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_detail_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
  'phases': z.union([z.undefined(), z.array(z.object({
  'title': z.string().readonly(),
  'detail': z.union([z.undefined(), z.string()]).readonly().optional(),
  'provider': z.union([z.undefined(), z.string()]).readonly().optional(),
  'model': z.union([z.undefined(), z.string()]).readonly().optional(),
}))]).readonly().optional(),
  'gate': z.union([z.undefined(), z.object({
  'id': z.union([z.undefined(), z.string()]).readonly().optional(),
  'kind': z.union([z.literal("user"), z.literal("back_off"), z.literal("no_progress"), z.literal("verification"), z.literal("infra")]).readonly(),
  'message': z.string().readonly(),
  'resumable': z.boolean().readonly(),
})]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
  'scriptPath': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_list_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_list_parameter_1$schema = z.object({
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const _zaalipro_dsh_workflows_workflowRuns_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'epoch': z.string().readonly(),
  'sessionRevision': z.number().readonly(),
  'items': z.array(z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'total': z.number().readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_logs_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_logs_parameter_1$schema = z.object({
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_logs_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'index': z.number().readonly(),
  'text': z.string().readonly(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'evicted': z.number().readonly(),
  'total': z.number().readonly(),
  'revision': z.number().readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_memberDetail_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_memberDetail_parameter_1$schema = z.object({
  'memberId': z.string().readonly(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_memberDetail_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'member': z.object({
  'memberId': z.string().readonly(),
  'seq': z.number().readonly(),
  'label': z.string().readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]).readonly(),
  'startedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'outcome': z.union([z.literal("pending"), z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'childSessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'childSessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'outcome': z.union([z.object({
  'state': z.union([z.literal("pending"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
}), z.object({
  'state': z.literal("available").readonly(),
  'content': z.union([z.object({
  'kind': z.literal("value").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)).readonly()]).readonly(),
}), z.object({
  'kind': z.literal("preview").readonly(),
  'text': z.string().readonly(),
})]).readonly(),
  'totalBytes': z.number().readonly(),
  'truncated': z.boolean().readonly(),
})]).readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_members_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_members_parameter_1$schema = z.object({
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_members_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'memberId': z.string().readonly(),
  'seq': z.number().readonly(),
  'label': z.string().readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.literal("running"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]).readonly(),
  'startedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'outcome': z.union([z.literal("pending"), z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'childSessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'total': z.number().readonly(),
  'revision': z.number().readonly(),
}).readonly(),
})])
const _zaalipro_dsh_workflows_workflowRuns_result_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _zaalipro_dsh_workflows_workflowRuns_result_parameter_1$schema = z.object({
  'runId': z.string().readonly(),
})
const _zaalipro_dsh_workflows_workflowRuns_result_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.union([z.literal("invalid-page-limit"), z.literal("invalid-artifact-limit"), z.literal("invalid-cursor"), z.literal("stale-cursor"), z.literal("workspace-unavailable"), z.literal("definition-invalid"), z.literal("run-not-found"), z.literal("member-not-found"), z.literal("artifact-not-found"), z.literal("artifact-changed"), z.literal("storage-unavailable")]).readonly(),
  'message': z.string().readonly(),
  'details': z.union([z.undefined(), z.object({
  'min': z.union([z.undefined(), z.number()]).readonly().optional(),
  'max': z.union([z.undefined(), z.number()]).readonly().optional(),
  'revision': z.union([z.undefined(), z.number()]).readonly().optional(),
})]).readonly().optional(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'message': z.literal("workflow run changed; refresh it before applying a control").readonly(),
  'details': z.object({
  'run': z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
}).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("action-unavailable").readonly(),
  'message': z.string().readonly(),
  'details': z.object({
  'reason': z.union([z.literal("budget-limited"), z.literal("invalid-state"), z.literal("save-ineligible")]).readonly(),
  'run': z.union([z.undefined(), z.object({
  'runId': z.string().readonly(),
  'displayName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'status': z.union([z.literal("running"), z.literal("pausing"), z.literal("stopping"), z.literal("needs-input"), z.literal("paused"), z.literal("budget-limited"), z.literal("completed"), z.literal("failed"), z.literal("cancelled"), z.literal("interrupted")]).readonly(),
  'phase': z.union([z.undefined(), z.string()]).readonly().optional(),
  'budget': z.object({
  'total': z.number().readonly(),
  'spent': z.number().readonly(),
  'remaining': z.number().readonly(),
}).readonly(),
  'memberCounts': z.object({
  'total': z.number().readonly(),
  'running': z.number().readonly(),
  'completed': z.number().readonly(),
  'failed': z.number().readonly(),
  'cancelled': z.number().readonly(),
}).readonly(),
  'startedAt': z.number().readonly(),
  'settledAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'terminal': z.union([z.undefined(), z.object({
  'stopReason': z.union([z.literal("completed"), z.literal("cancelled"), z.literal("interrupted"), z.literal("error")]).readonly(),
  'resultState': z.union([z.literal("available"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
  'preview': z.union([z.undefined(), z.string()]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'allowedActions': z.array(z.union([z.literal("pause"), z.literal("resume"), z.literal("stop"), z.literal("save")])).readonly(),
  'revision': z.number().readonly(),
  'detailRevision': z.number().readonly(),
  'membersRevision': z.number().readonly(),
  'logsRevision': z.number().readonly(),
  'resultRevision': z.number().readonly(),
  'artifactsRevision': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'value': z.union([z.object({
  'state': z.union([z.literal("pending"), z.literal("not-produced"), z.literal("evicted")]).readonly(),
}), z.object({
  'state': z.literal("available").readonly(),
  'content': z.union([z.object({
  'kind': z.literal("value").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema2)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)).readonly()]).readonly(),
}), z.object({
  'kind': z.literal("preview").readonly(),
  'text': z.string().readonly(),
})]).readonly(),
  'totalBytes': z.number().readonly(),
  'truncated': z.boolean().readonly(),
})]).readonly(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@zaalipro/dsh-workflows',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@zaalipro/dsh-workflows#workflowDefinitions/list',
      service: 'workflowDefinitionsRemote',
      namespace: 'workflowDefinitions',
      method: 'list',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowDefinitions_list_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/registry#WorkflowDefinitionListRequest',
            schema: _zaalipro_dsh_workflows_workflowDefinitions_list_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowDefinitions_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/registry/remote.ts","line":51,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/artifact',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'artifact',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_artifact_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunArtifactRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_artifact_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_artifact_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":350,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/artifacts',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'artifacts',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_artifacts_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunArtifactsRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_artifacts_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_artifacts_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":344,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/control',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'control',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_control_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunControlRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_control_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_control_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":413,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/detail',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'detail',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_detail_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_detail_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_detail_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":247,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/list',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'list',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_list_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunListRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_list_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":194,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/logs',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'logs',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_logs_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunLogsRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_logs_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_logs_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":325,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/memberDetail',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'memberDetail',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_memberDetail_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunMemberRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_memberDetail_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_memberDetail_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":312,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/members',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'members',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_members_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunMembersRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_members_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_members_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":306,"column":9},
    },
    {
      id: '@zaalipro/dsh-workflows#workflowRuns/result',
      service: 'workflowRunsRemote',
      namespace: 'workflowRuns',
      method: 'result',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _zaalipro_dsh_workflows_workflowRuns_result_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRunRequest',
            schema: _zaalipro_dsh_workflows_workflowRuns_result_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@zaalipro/dsh-workflows/supervisor#WorkflowRemoteResult',
        schema: _zaalipro_dsh_workflows_workflowRuns_result_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-workflows/src/supervisor/remote.ts","line":331,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "tags": [],
        "name": "workflows/gate-request",
        "signature": "'workflows/gate-request'(request: WorkflowGateRequest): void"
      },
      {
        "tags": [],
        "name": "workflows/member-end",
        "signature": "'workflows/member-end'(info: SupervisedWorkflowRunInfo, member: SupervisedWorkflowMemberLifecycleInfo): void"
      },
      {
        "tags": [],
        "name": "workflows/member-start",
        "signature": "'workflows/member-start'(info: SupervisedWorkflowRunInfo, member: SupervisedWorkflowMemberLifecycleInfo): void"
      },
      {
        "description": "Invalidation-only workflow run hint. Never carries a run head.",
        "summary": "Invalidation-only workflow run hint.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Invalidation-only workflow run hint. Never carries a run head.\n * @mode emit\n */",
        "name": "workflows/run-change",
        "mode": "emit",
        "signature": "'workflows/run-change'(change: WorkflowRunChange): void"
      },
      {
        "tags": [],
        "name": "workflows/run-end",
        "signature": "'workflows/run-end'(info: SupervisedWorkflowRunInfo, result: SupervisedWorkflowResultInfo): void"
      },
      {
        "tags": [],
        "name": "workflows/run-start",
        "signature": "'workflows/run-start'(info: SupervisedWorkflowRunInfo): void"
      }
    ],
    "objects": []
  },
}
