/** Saved workflow definition registry. */
import { constants } from 'node:fs';
import { lstat, mkdir, open, readdir, readFile, rename, stat, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { parseDefinitionFile, serializeDefinition, validateDefinitionEnvelope, filenameStem } from './definition.js';
import { isWorkflowDefinitionName, assertWorkflowDefinitionName, isWorkflowName } from './names.js';
import { resolveWorkflowRoots } from './roots.js';
import type { WorkflowCatalogSnapshot, WorkflowDefinition, WorkflowDefinitionEnvelope, WorkflowDefinitionListPage, WorkflowDefinitionListRequest, WorkflowDefinitionSummary, WorkflowLookupOptions, WorkflowSaveOptions, WorkflowScope, RegistryConfig } from './types.js';
export * from './types.js'; export * from './names.js'; export * from './definition.js'; export * from './roots.js';

export class WorkflowRegistryError extends Error { readonly code: string; constructor(message:string,code='WORKFLOW_DEFINITION_INVALID',options?:ErrorOptions){super(message,options);this.name='WorkflowRegistryError';this.code=code;} }
interface ContextLike { fs?: any; on?: (event:string,listener:()=>void)=>()=>void; emit?: (event:string,...args:unknown[])=>void; effect?: (fn:()=>unknown,...args:unknown[])=>unknown; logger?: {warn(...args:unknown[]):void} }
const decoder = new TextDecoder('utf-8',{fatal:true});
async function readNoFollow(path:string,max:number,signal?:AbortSignal):Promise<Uint8Array>{
 signal?.throwIfAborted(); let fh; try { fh=await open(path,constants.O_RDONLY|((constants as any).O_NOFOLLOW??0)); const s=await fh.stat(); if(!s.isFile()||s.nlink>1)throw new WorkflowRegistryError(`${path}: workflow definition must be a regular file and not a link`); if(s.size>max)throw new WorkflowRegistryError(`${path}: definition exceeds ${max} bytes`); const out=Buffer.alloc(Math.min(max+1,64*1024)); const chunks:Buffer[]=[];let total=0;while(total<=max){signal?.throwIfAborted();const b=Buffer.alloc(Math.min(out.length,max+1-total));const {bytesRead}=await fh.read(b,0,b.length,null);if(!bytesRead)break;chunks.push(b.subarray(0,bytesRead));total+=bytesRead;if(total>max)throw new WorkflowRegistryError(`${path}: definition exceeds ${max} bytes`)}return new Uint8Array(Buffer.concat(chunks));}catch(e){if(e instanceof WorkflowRegistryError)throw e;const code=(e as NodeJS.ErrnoException).code;if(code==='ENOENT')throw new WorkflowRegistryError(`${path}: definition not found`,'WORKFLOW_DEFINITION_INVALID',{cause:e});throw e;}finally{await fh?.close().catch(()=>{});}}
async function existsDirectory(path:string):Promise<boolean>{try{const s=await lstat(path);return s.isDirectory()&&!s.isSymbolicLink()}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return false;throw e}}

/** Registry implementation; context integration is optional for headless/unit use. */
export class WorkflowRegistry {
 static readonly inject = ['fs'] as const;
 readonly config: Required<Pick<RegistryConfig,'enabled'|'definitionWatch'|'definitionMaxBytes'|'maxDefinitionsPerRoot'|'watchMaxProjects'|'watchStabilityThresholdMs'|'watchPollIntervalMs'>> & RegistryConfig;
 private readonly ctx?: ContextLike; private readonly dshHome:string; private revision=0; private disposed=false; private watchers: Array<{close():void}>=[]; private refreshTimer?:NodeJS.Timeout;
 constructor(ctxOrConfig?: ContextLike|RegistryConfig, config?: RegistryConfig){ this.ctx = config ? ctxOrConfig as ContextLike : undefined; const c=config ?? ctxOrConfig as RegistryConfig ?? {}; this.dshHome=resolve(c.dshHome ?? process.env.DSH_HOME ?? process.cwd()); this.config={enabled:c.enabled??true,definitionWatch:c.definitionWatch??true,definitionMaxBytes:c.definitionMaxBytes??1_048_576,maxDefinitionsPerRoot:c.maxDefinitionsPerRoot??256,watchMaxProjects:c.watchMaxProjects??128,watchStabilityThresholdMs:c.watchStabilityThresholdMs??200,watchPollIntervalMs:c.watchPollIntervalMs??100,...c}; if(this.config.definitionWatch)this.installWatchers(); }
 private async roots(options:WorkflowLookupOptions={}) { return resolveWorkflowRoots({cwd:options.cwd,dshHome:this.dshHome,bundledDefinitionsDir:this.config.bundledDefinitionsDir,signal:options.signal}); }
 private emitChange(){if(this.disposed)return;this.revision++;if(this.refreshTimer)clearTimeout(this.refreshTimer);this.refreshTimer=setTimeout(()=>{if(!this.disposed)this.ctx?.emit?.('workflows/change')},0);}
 private async installWatchers(){ /* root watchers are best-effort invalidation only; discovery remains authoritative */ }
 /** List winning definitions sorted by name. */
 async list(options:WorkflowLookupOptions={}):Promise<readonly WorkflowDefinitionSummary[]>{if(!this.config.enabled)return [];const roots=await this.roots(options);const winners=new Map<string,WorkflowDefinitionSummary>();for(const root of roots){if(!(await existsDirectory(root.path)))continue;const entries=await readdir(root.path,{withFileTypes:true});let count=0;for(const entry of entries){if(!entry.name.endsWith('.workflow.json')||entry.name.includes('/')||entry.isSymbolicLink())continue;const stem=filenameStem(entry.name);if(!isWorkflowDefinitionName(stem))throw new WorkflowRegistryError(`${join(root.path,entry.name)}: invalid workflow filename`);if(++count>this.config.maxDefinitionsPerRoot)throw new WorkflowRegistryError(`${root.path}: exceeds ${this.config.maxDefinitionsPerRoot} definitions`);if(winners.has(stem))continue;const path=join(root.path,entry.name);const raw=decoder.decode(await readNoFollow(path,this.config.definitionMaxBytes,options.signal));const parsed=parseDefinitionFile(raw,path,stem);winners.set(stem,{...parsed,scope:root.scope});}}return [...winners.values()].sort((a,b)=>a.name.localeCompare(b.name));}
 /** Return a bounded catalog observation. */
 async snapshot(options:WorkflowLookupOptions={}):Promise<WorkflowCatalogSnapshot>{if(!this.config.enabled)return {definitions:[],complete:true};return {definitions:await this.list(options),complete:true,revision:this.revision};}
 /** Resolve one winning full definition. */
 async get(name:string,options:WorkflowLookupOptions={}):Promise<WorkflowDefinition|undefined>{assertWorkflowDefinitionName(name,'workflow lookup');if(!this.config.enabled)return undefined;const roots=await this.roots(options);for(const root of roots){const path=join(root.path,`${name}.workflow.json`);try{const raw=decoder.decode(await readNoFollow(path,this.config.definitionMaxBytes,options.signal));return {...parseDefinitionFile(raw,path,name),scope:root.scope};}catch(e){if(e instanceof WorkflowRegistryError && /not found/u.test(e.message))continue;if((e as NodeJS.ErrnoException)?.code==='ENOENT')continue;throw e;}}return undefined;}
 /** Publish a project/user definition using canonical bytes and guarded replacement. */
 async save(envelope:WorkflowDefinitionEnvelope,options:WorkflowSaveOptions):Promise<WorkflowDefinition>{if(!this.config.enabled)throw new WorkflowRegistryError('workflow registry is disabled','WORKFLOW_REGISTRY_DISABLED');const clean=validateDefinitionEnvelope(envelope);const roots=await this.roots(options);const root=roots.find(r=>r.scope===options.scope)!;await mkdir(root.path,{recursive:true,mode:0o700});const path=join(root.path,`${clean.meta.name}.workflow.json`);const bytes=serializeDefinition(clean);options.signal?.throwIfAborted();const tmp=join(root.path,`.${clean.meta.name}.${randomBytes(12).toString('hex')}.tmp`);let created=false;try{await writeFile(tmp,bytes,{encoding:'utf8',flag:'wx',mode:0o600});created=true;try{await lstat(path);await rename(tmp,path); }catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT'){await rename(tmp,path)}else throw e;}this.emitChange();return {...parseDefinitionFile(bytes,path,clean.meta.name),scope:options.scope};}finally{if(created)await unlink(tmp).catch(()=>{});}}
 /** Registry Remote-style paginated list. */
 async listPage(_agent: unknown, request:WorkflowDefinitionListRequest={}, options:WorkflowLookupOptions={}):Promise<{ok:true,value:WorkflowDefinitionListPage}|{ok:false;error:string;code:string}>{const limit=request.limit??50;if(!Number.isSafeInteger(limit)||limit<1||limit>200)return {ok:false,error:'workflow page limit must be a safe integer from 1 through 200',code:'invalid-page-limit'};const items=await this.list(options);const offset=request.cursor?Number(request.cursor):0;if(!Number.isSafeInteger(offset)||offset<0||offset>items.length)return {ok:false,error:'workflow page cursor is invalid or belongs to another collection',code:'invalid-cursor'};const slice=items.slice(offset,offset+limit).map(({name,description,whenToUse,scope})=>({name,description,...(whenToUse===undefined?{}:{whenToUse}),scope}));return {ok:true,value:{items:slice,total:items.length,revision:this.revision,...(offset+limit<items.length?{nextCursor:String(offset+limit) as any}: {})}};}
 async dispose(){this.disposed=true;if(this.refreshTimer)clearTimeout(this.refreshTimer);for(const w of this.watchers)w.close();this.watchers=[];}
}
export class WorkflowDefinitionsRemote { static readonly inject=['workflows'] as const; constructor(private readonly registry:WorkflowRegistry){} async list(agent:unknown,request:WorkflowDefinitionListRequest,signal:AbortSignal){return this.registry.listPage(agent,request, {signal});} }
